### ISSUE TITLE
Misaligned

### ISSUE THREAD

**Issue by Jishnukj** [brijeshpthankachan/StudentMS#12]
![image](https://github.com/brijeshpthankachan/StudentMS/assets/38211684/a00453a1-266c-415c-b21a-6d53a9dd4136)

line 34, 45

alignment is not proper

**Comment by brijeshpthankachan** [comment]
It's wrapped, seems well aligned in full screen

**Comment by Jishnukj** [comment]
![image](https://github.com/brijeshpthankachan/StudentMS/assets/38211684/3ab3ca8c-b8b3-4873-934d-7c090f65ae64)

Still, I can see the issue. The position  of { } in this file is different from others

refer
![image](https://github.com/brijeshpthankachan/StudentMS/assets/38211684/6686ce92-9d26-4e86-9d00-ea3850b3bcab)

**Comment by brijeshpthankachan** [comment]
probably it is wrapped, moved it to the next line, seems fine in my ide
