### ISSUE TITLE
End point correction

### ISSUE THREAD

**Issue by Jishnukj** [brijeshpthankachan/StudentMS#13]
![image](https://github.com/brijeshpthankachan/StudentMS/assets/38211684/92e308cf-627c-4104-9592-68609cd8ad31)

Update end point

Suggestion : marks/students/{studentId}/subjects/{subjectId}

**Comment by brijeshpthankachan** [comment]
changed

**Comment by Jishnukj** [comment]
Last commit 4 days ago? Did you push the code?

**Comment by brijeshpthankachan** [comment]
yes
